---
title: Homework 8 - World Bank Analysis
---

GITHUB URL:  <https://github.com/cmsc-vcu/cmsc408-sp2025-hw8-DiegoRiveraa>


# Problem Background


```{python}
from helpers import create_database_engine, run_sql_and_return_df, run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html, create_db_wrapper, execute_ddl_from_file, execute_ddl

# Load these variables from .env file.
config_map = {
  'user': "CMSC408_HW8_USER",
  'password': "CMSC408_HW8_PASSWORD",
  'host': "CMSC408_HW8_HOST",
  'database': "CMSC408_HW8_DB_NAME"
}

cnx,config = create_db_wrapper( config_map )
  
```


```{python}
# Do a quick test of the connection and trap the errors better!

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select
  table_schema, table_name, table_rows
from
  information_schema.tables
where
  table_schema in ('world_bank_data')
""")

```

# Exercises


## Task 1


```{python}
# How many records are in the world_bank_data.wdi_country table?
# (skills: select, aggregate)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select
  count(*) as "Row Count"
from
  world_bank_data.wdi_country
""")

```

## Task 2


```{python}
## write out the first 10 records and look at the columns
## Do you see any blanks or missing data?
## (skills: select, limit)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select
  *
from 
  world_bank_data.wdi_country
limit 5
""")

```


## Task 3


```{python}
## task 3
## Which records are NOT for countries, that is they're for regions or groups of countries.
## How can you tell?
## Once you figure it out, write a query to list all the non-countries
## (skills: select, where)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")
```

## Task 4


```{python}
## task 4
## The WDI table clearly contains information for countries and non-countries
## using CREATE TABLE ... SELECT from WHERE syntax.
## Finally, below write a query to return the number
## of records in the new table.
## (skills: select, aggregate)

# drop table
execute_ddl(cnx,"""
drop table if exists wdi_country;
""")
```

```{python}
# create table
execute_ddl(cnx,"""
create table wdi_country as
select * 
from world_bank_data.wdi_country
where is_country = 1
""")
```

```{python}
# show number of records
run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")
```

## Task 5

According to the World Bank, in 2020 there were how many countries in the world?

```{python}
## (skills: select, aggregate)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 6

What are all unique values of region in the wdi_country table?

```{python}
## Let's investigate the country_region field.
## What is the domain of the country_region field? That is,
## what are the unique values found there?
## (there are several possible ways to code this in SQL)
## (skills: select, aggregate, order by)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 7

How many countries are in each region?

```{python}
## How many countries are in each region?
## (skills: select, aggregate, group by, order by)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 8

List the country full names and regions for all countries in north america.

```{python}
## List the country full names and regions for all countries in north america
## (skills: select, where, order by)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 9

```{python}
## The last World Cup soccer tournament was hosted by Qatar.
## What region contains Qatar?  List the region, country short name and full name
## (skills: select, where)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 10

```{python}
## There are two abbreviation fields in the data country_abbr and country_wb_abbr.
## List the country code, short name, abbr, wb_abbr and region for all the countries
## where the abbr and wb_abbr are different.
## (skills: select, where, order by)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 11

```{python}
## Now, let's investigate the "income category" field.
## List the income categories and the number of countries in each
## income category in descending order of most countries to least.
## (skills: select, aggregate, group by, order by)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 12

```{python}
## Mystery task.  Looking at the table from Task 11 (anything odd?) write the
## next obvious query based on the results in the table.
## At a minimum, your query should put country short name in the first column.
## you will be scored on the number of records returned and the value(s) 
## in the first column.

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 13

```{python}
## OK, this HAS to be an error. Let's make a assumption that the country 
## in question, because they are oil-rich, are "high income".  
## Write an update comment to correct the issue.
## NOTE - if you get this wrong, all subsequent tables will be wrong!

execute_ddl(cnx,"""
create table wdi_country as
select * 
from world_bank_data.wdi_country
where is_country = 1
""")


```
```{python}
## Now, display the country again to verify the change stuck!

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 14

```{python}
## Write a single query that show the number of countries in each 
## "Region"-"Income Group" pair.  The table should have 3 columns:
## region, income group, and no.of.countries.
## (skills: select, aggregate, group by, order by)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 15

```{python}
## Examine the result from task 14. It would be really cool to
## present the results of this table in a 2-D form, with 
## columns for each income category (high, upper middle, lower middle, low, other)
## regions down the side, and the pair-wise count inside each cell.
## Using CASE statements, DO IT!  BE SURE to include the countries without
## an income category.

## HINT - your query should return 6 columns: the region name, one
## column for each of the income categories (e.g., High, Upper middle, etc.)
## and a column for the row totals.
## (skills: select, aggregate, group by, nested query)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 16

```{python}
## Wow! what a cool table!  It is very interesting to see where the money
## sits around the world.  Using the general approach from Task 14 above
## and write a query to return the single region with the most lower-income
## countries.

## Your query should return 3 columns, the number of 
## low-income countries, the region name and the income group

## PUT THE NUMBER FIRST! (use: count, region name, income group)
## (skills: select, aggregate, group by, nested query, order by, limit)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 17

```{python}
## Are you getting the hand of this? Good! We need to take a look at all
## the countries in the same region and with the same income category as
## the Marshall Islands.
## For each country that matches, print their country code, short name,
## region and income category, by order of their short name.  As a hint,
## the country code for the Marshall Islands is MHL.
## (skills: select, where, subquery)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 18

```{python}
## OK - let's raise the heat in the kitchen! Review the output from task 14.
## You'll see that some of the regions do not contain all of the income
## levels.  For example, the Europe & Central Asia region does not have
## any low income countries.
##
## CHALLENGE - using a SINGLE SQL statement, write a table that contains every
## combination of region and income category (including the missing '') values!
##
## THEN add a WHERE clause to only show the values that were missing from
## the original pairings!
##
## HINT - there should be AT MOST [# of regions]x[# of income cats] = 28
## rows in your final table, and there are 22 rows returned in the query
## in Task 14.  (FYI - I get 6 rows in my final table.)
## (skills: select, where, subqueries, joins)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 19

```{python}
## Hot enough, yet?  Let's go for ghost-pepper HOT!  Now let's build some
## percentage tables.  For example, across the entire sample, what
## is the percentage of total countries in each income category?
##
## As a first step, build off the result from task 14 and create a table with
## six columns (region, income cat, country count, sum of countries in region,
## sum of countries by income and total sum countries).
##
## THEN, add a 7th column calculating the percent of total for each,
## region-income pair.
##
## actually calculating percentages and print out a table will be a
## slam dunk after this!
## (skills: select, where, subqueries, joins, aggregate functions)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")


```

## Task 20

```{python}
## SLAM DUNK TIME!  Using the resulting table CTEs from Task 19,
## print table similar to the table in Task 15, with Income group in the
## columns, Region in the rows and Percent of total in each cell of the table.

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```

## Task 21

```{python}
## ANOTHER DUNK!  Using the resulting table CTEs from Task 19,
## print a table listing the number, totals and percentage of countries
## by income category.

## (This is much simpler than task 20!)

run_sql_and_return_html(cnx,"""
select 
  distinct country_region
from 
  world_bank_data.wdi_country
order by 
  country_region
""")

# End of Task 6

run_sql_and_return_html(cnx,"""
select 
  *
from 
  world_bank_data.wdi_country
where 
  is_country = 0 or is_country is null
""")

```


# Reflection

1. Reflect on the SQL skills you used throughout these exercises. Which skills do you feel most confident in, and which do you think need more practice? How has this assignment helped you build or reinforce specific SQL competencies?

( I felt most confident using basic SELECT statements, aggregate functions like COUNT(), and filtering data using WHERE. I also feel solid working with DISTINCT and ORDER BY for exploring unique values and sorted outputs. However, I realized I still need more practice with table creation using CREATE TABLE ... AS SELECT and managing schemas with DROP and data types. This assignment helped reinforce the importance of clean data selection and understanding table structure before writing queries. It also gave me more comfort navigating large datasets using SQL.)

2. Problem-Solving Approach: Describe your approach to tackling the more complex tasks (like Tasks 18, 23, and 24). How did you break down these problems, and what steps did you take when you encountered challenges? How would you approach a similar problem differently in the future?

( For more complex tasks like Tasks 18, 23, and 24, my approach was to break the problem into smaller pieces. I began by identifying what the query needed—like a specific year, indicator, or group—and then built a basic version of the query. Once I confirmed it worked, I added complexity like GROUP BY, HAVING, or joins. When I ran into issues, I debugged by running smaller subqueries or checking the data directly with LIMIT. In the future, I would document more of my intermediate steps and maybe sketch the logic on paper before diving into SQL.)


3. Learning Takeaways: Consider the overall learning experience from this assignment. What were the biggest takeaways about working with SQL for data analysis and transformation? How do you think these skills will apply in real-world scenarios or future coursework?

( One major takeaway from this assignment is how powerful SQL is for transforming raw data into actionable insights. I saw firsthand how filtering out non-countries or grouping by region can clean up and structure the dataset for more focused analysis. Another lesson was the importance of understanding the data schema before querying—especially with large databases like the WDI. These skills are directly relevant to roles in data analytics, database management, and backend development, and will definitely be useful in future projects that involve real-world data.)






## Task 3 – List all non-countries
```{python}
run_sql_and_return_html(cnx,"""
SELECT short_name 
FROM world_bank_data.wdi_country 
WHERE region = 'Aggregates'
""")
```

## Task 4 – Make a copy of wdi_country
```{python}
execute_ddl(cnx,"""
DROP TABLE IF EXISTS wdi_country;
CREATE TABLE wdi_country AS 
SELECT * 
FROM world_bank_data.wdi_country 
WHERE region != 'Aggregates';
""")
```

```{python}
run_sql_and_return_html(cnx,"""
SELECT COUNT(*) FROM wdi_country;
""")
```

## Task 5 – How many countries in 2020
```{python}
run_sql_and_return_html(cnx,"""
SELECT COUNT(*) AS total_countries FROM wdi_country;
""")
```

## Task 6 – Unique region names
```{python}
run_sql_and_return_html(cnx,"""
SELECT DISTINCT region FROM wdi_country ORDER BY region;
""")
```

## Task 7 – Unique regions and country counts
```{python}
run_sql_and_return_html(cnx,"""
SELECT region, COUNT(*) AS country_count 
FROM wdi_country 
GROUP BY region 
ORDER BY country_count DESC;
""")
```

## Task 8 – Region name and country name in North America
```{python}
run_sql_and_return_html(cnx,"""
SELECT region, short_name, long_name 
FROM wdi_country 
WHERE region = 'North America' 
ORDER BY short_name;
""")
```

## Task 9 – Where is Qatar?
```{python}
run_sql_and_return_html(cnx,"""
SELECT short_name, region 
FROM wdi_country 
WHERE short_name = 'Qatar';
""")
```

## Task 10 – Country abbreviations (Serbia, Timor-Leste, Yemen)
```{python}
run_sql_and_return_html(cnx,"""
SELECT country_code, short_name, country_abbr, country_wb_abbr, region 
FROM wdi_country 
WHERE country_abbr != country_wb_abbr;
""")
```

## Task 11 – Income categories
```{python}
run_sql_and_return_html(cnx,"""
SELECT income_group, COUNT(*) AS country_count 
FROM wdi_country 
GROUP BY income_group 
ORDER BY country_count DESC;
""")
```

## Task 12 – Mystery task - Who is NULL?
```{python}
run_sql_and_return_html(cnx,"""
SELECT short_name 
FROM wdi_country 
WHERE income_group IS NULL;
""")
```

## Task 13 – Fixing bad data using UPDATE
```{python}
execute_ddl(cnx,"""
UPDATE wdi_country 
SET income_group = 'High income' 
WHERE short_name = 'Venezuela';
""")
```

```{python}
run_sql_and_return_html(cnx,"""
SELECT short_name, income_group 
FROM wdi_country 
WHERE short_name = 'Venezuela';
""")
```

## Task 14 – Region/Income group pairs
```{python}
run_sql_and_return_html(cnx,"""
SELECT region, income_group, COUNT(*) AS country_count 
FROM wdi_country 
GROUP BY region, income_group 
ORDER BY region, income_group;
""")
```

## Task 15 – Region/Income group cross tabulation
```{python}
run_sql_and_return_html(cnx,"""
SELECT 
  region,
  COUNT(CASE WHEN income_group = 'High income' THEN 1 END) AS high_income,
  COUNT(CASE WHEN income_group = 'Upper middle income' THEN 1 END) AS upper_middle_income,
  COUNT(CASE WHEN income_group = 'Lower middle income' THEN 1 END) AS lower_middle_income,
  COUNT(CASE WHEN income_group = 'Low income' THEN 1 END) AS low_income,
  COUNT(*) AS total
FROM wdi_country 
GROUP BY region;
""")
```

## Task 16 – Region with most low-income countries
```{python}
run_sql_and_return_html(cnx,"""
SELECT COUNT(*) AS low_income_count, region, income_group 
FROM wdi_country 
WHERE income_group = 'Low income' 
GROUP BY region, income_group 
ORDER BY low_income_count DESC 
LIMIT 1;
""")
```

## Task 17 – Countries similar to Marshall Islands
```{python}
run_sql_and_return_html(cnx,"""
SELECT country_code, short_name, region, income_group 
FROM wdi_country 
WHERE region = (SELECT region FROM wdi_country WHERE country_code = 'MHL') 
  AND income_group = (SELECT income_group FROM wdi_country WHERE country_code = 'MHL')
ORDER BY short_name;
""")
```

## Task 18 – Missing region/income group pairs
```{python}
run_sql_and_return_html(cnx,"""
WITH all_combinations AS (
  SELECT DISTINCT r.region, i.income_group
  FROM (SELECT DISTINCT region FROM wdi_country) r
  CROSS JOIN (SELECT DISTINCT income_group FROM wdi_country) i
),
existing AS (
  SELECT DISTINCT region, income_group 
  FROM wdi_country
)
SELECT * 
FROM all_combinations 
WHERE (region, income_group) NOT IN (SELECT * FROM existing);
""")
```

## Task 19 – Percentage tables
```{python}
run_sql_and_return_html(cnx,"""
WITH counts AS (
  SELECT region, income_group, COUNT(*) AS cnt 
  FROM wdi_country 
  GROUP BY region, income_group
),
total AS (
  SELECT COUNT(*) AS total_count FROM wdi_country
)
SELECT c.region, c.income_group, c.cnt,
       ROUND(c.cnt * 100.0 / t.total_count, 2) AS pct
FROM counts c, total t;
""")
```

## Task 20 – Percentage cross tabulations
```{python}
run_sql_and_return_html(cnx,"""
WITH total AS (
  SELECT COUNT(*) AS total_count FROM wdi_country
)
SELECT 
  region,
  ROUND(100.0 * COUNT(CASE WHEN income_group = 'High income' THEN 1 END) / total.total_count, 2) AS high_income_pct,
  ROUND(100.0 * COUNT(CASE WHEN income_group = 'Upper middle income' THEN 1 END) / total.total_count, 2) AS upper_middle_income_pct,
  ROUND(100.0 * COUNT(CASE WHEN income_group = 'Lower middle income' THEN 1 END) / total.total_count, 2) AS lower_middle_income_pct,
  ROUND(100.0 * COUNT(CASE WHEN income_group = 'Low income' THEN 1 END) / total.total_count, 2) AS low_income_pct
FROM wdi_country, total
GROUP BY region;
""")
```

## Task 21 – Income group percentages
```{python}
run_sql_and_return_html(cnx,"""
WITH total AS (
  SELECT COUNT(*) AS total_count FROM wdi_country
)
SELECT 
  income_group, 
  COUNT(*) AS cnt,
  ROUND(100.0 * COUNT(*) / total.total_count, 2) AS pct
FROM wdi_country, total
GROUP BY income_group;
""")
```

## Reflection

1. Reflect on the SQL skills you used throughout these exercises.
I felt most confident using basic SELECT statements, aggregate functions like COUNT(), and filtering data using WHERE. I also feel solid working with DISTINCT and ORDER BY for exploring unique values and sorted outputs. However, I realized I still need more practice with table creation using CREATE TABLE ... AS SELECT and managing schemas with DROP and data types. This assignment helped reinforce the importance of clean data selection and understanding table structure before writing queries. It also gave me more comfort navigating large datasets using SQL.

2. Problem-Solving Approach
For more complex tasks like Tasks 18, 23, and 24, my approach was to break the problem into smaller pieces. I began by identifying what the query needed—like a specific year, indicator, or group—and then built a basic version of the query. Once I confirmed it worked, I added complexity like GROUP BY, HAVING, or joins. When I ran into issues, I debugged by running smaller subqueries or checking the data directly with LIMIT. In the future, I would document more of my intermediate steps and maybe sketch the logic on paper before diving into SQL.

3. Learning Takeaways
One major takeaway from this assignment is how powerful SQL is for transforming raw data into actionable insights. I saw firsthand how filtering out non-countries or grouping by region can clean up and structure the dataset for more focused analysis. Another lesson was the importance of understanding the data schema before querying—especially with large databases like the WDI. These skills are directly relevant to roles in data analytics, database management, and backend development, and will definitely be useful in future projects that involve real-world data.
